### ISSUE TITLE
Feature priorities

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#12]
1. XY plots of fault-parallel and fault-perpendicular cross sections and seismicity versus time via Python (Brad’s scripts)
    * Parameters
        * fault strike (default could be one plane from the focal mechanism)
        * cross section width (default = 5 km)
2. Add map layers with information from event page
    1. Mainshock focal mechanisn (image on map)
    2. Mainshock moment tensor (image on map)
    3. ShapeMap stations (triangles colored by intensity like on event page interactive map)
3. Separate historical seismicity into "significant" and non-significant events
    * Use different magnitude minimum thresholds and maximum distances for significant and historical events.
    * Replace dots for mainshock and significant events with focal mechanisms or moment tensors?
    * Add macro seismic comment from ComCat for significant events?
4. Migrate Python scripts for XY plots to Javascript

**Comment by baagaard-usgs** [comment]
For the originTime we should use a time zone aware format.

For the API to plotting scripts, how about a json string corresponding to:

```
{
    "mainshock": {
        "originTime": "2014-08-24T3:20:44",
        "magnitude": 6.0,
	"latitude": 38.215,
	"longitude": -122.312,
        "depth": 11.1
    },
    "aftershocks": [
	{
	    "originTime": "2014-08-24T3:21:45",
	    "magnitude": 3.8,
	    "latitude": 38.235,
	    "longitude": -122.320,
	    "depth": 9.1
	},
	{
	    "originTime": "2014-08-24T3:24:44",
	    "magnitude": 3.5,
	    "latitude": 38.260,
	    "longitude": -122.337,
	    "depth": 10.5
	},
	{
	    "originTime": "2014-08-24T5:47:12",
	    "magnitude": 3.6,
	    "latitude": 38.238,
	    "longitude": -122.342,
	    "depth": 8.5
	},
	{
	    "originTime": "2014-08-24T5:33:16",
	    "magnitude": 3.9,
	    "latitude": 38.179,
	    "longitude": -122.301,
	    "depth": 12.6
	},
	{
	    "originTime": "2014-08-26T4:33:22",
	    "magnitude": 3.7,
	    "latitude": 38.166,
	    "longitude": -122.300,
	    "depth": 10.4
	},
	{
	    "originTime": "2014-08-31T1:56:20",
	    "magnitude": 3.2,
	    "latitude": 38.236,
	    "longitude": -122.328,
	    "depth": 9.6
	}
    ],
    "historical": [
	{
	    "originTime": "2000-09-03T8:36:30",
	    "magnitude": 5.0,
	    "latitude": 38.379,
	    "longitude": -122.413,
	    "depth": 10.2
	}
    ]
}
```

**Comment by shaefner-usgs** [comment]
It would be easiest / most efficient to pass eqs in as geojson data using the existing schema, which is documented in the feed api (for aftershocks/historical) here: 

http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php

The mainshock is similar to this format:

http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson_detail.php

The app is already consuming json data in this format to create the map layers and summaries, and it could just pass on the same data to the cross section api without reformatting it.

**Comment by shaefner-usgs** [comment]
> Add macro seismic comment from ComCat for significant events?

What does this refer to in your original comment?

**Comment by baagaard-usgs** [comment]
See Paul Earle's request in Issue #10. I would put this on the long-term TODO list. The other current changes we have discussed (plots of historical seismicity, adding event id, etc) should have higher priority.

**Comment by shaefner-usgs** [comment]
Closing b/c this list is complete, except for the final bullet on item 3, which is referenced in [issue #10](https://github.com/shaefner-usgs/esc-eq-response/issues/10).
