### ISSUE TITLE
Refresh resets the parameters to the defaults

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#14]
Reloading a page resets the parameters to the default values based on the magnitude.

http://escweb.wr.usgs.gov/response/?eqid=us20007z6r&aftershocks-dist=60&historical-dist=100&historical-years=15#summary

Current behavior: Reloading the above will reset the historical-dist to 90 and the historical-years to 10.

Desired behavior: Reloading should maintain the same parameters. #

**Comment by shaefner-usgs** [comment]
This is a tricky issue to resolve. The app was previously configured to leave values alone that were entered by users. But this leads to undesirable behavior where default values don't always get set properly based on event magnitude, so I changed it to set default values regardless. Now this is leading to undesirable behavior b/c reloading the app resets the defaults.

Does that make sense? I'm not sure how to have it both ways...

**Comment by baagaard-usgs** [comment]
Update: Non defaults parameters are also ignored when entering the URL directly. **This is definitely not what we want.**

I think we need to separate the behavior for editing parameters on the edit pane and loading or reloading a page with a given URL. Can we just set a flag when the event id is changed from the edit panel and only reset the other parameters if the flag is set?

**Comment by shaefner-usgs** [comment]
It's not that easy b/c the value of that field changes on the initial load too (from empty to the event id in the query string).

I came up with a patch (which is actually pretty simple once I wrapped my head around it):

https://github.com/shaefner-usgs/esc-eq-response/commit/9d2385629bc71ce57dc116895b2a8a46a3bff135#diff-454fe9a20ee6a77b02e7a942dd7f9707
