### ISSUE TITLE
Separate pre-mainshock earthquakes into "Significant" and "Historical" earthquakes

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#20]
# Issue
We generally want to know what significant earthquakes have occurred near a mainshock in the past as well as what small earthquakes may have occurred leading up to a mainshock. This is particularly true in high seismicity areas (e.g., Brawley seismic zone).

# Proposed solution
Separate the current "Historical" earthquakes into "Significant" and "Historical" (recent?) earthquakes, where "Significant" has a higher minimum magnitude threshold and longer time span.

A possible naming scheme to differentiate between the significant earthquake drop-down menu, significant pre-mainshock earthquakes, small pre-mainshock earthquakes, and aftershocks would be to use "historical-significant" or "prior-significant" variables names for the pre-mainshock signifcant events  and "historical-recent" or "prior-recent" for the pre-mainshock recent events. I think my preference would be historical-significant.

## Historical Eqs
* significant-minmag: `Math.max(4.0, mag-2)`
* significant-dist: `Math.max(20, 15 * Math.round(0.1 * ruptureLength))`
* significant-years: `10`
## Foreshocks
* recent-minmag: `1.0`
* recent-dist: `Math.max(5, 10 * Math.round(0.1 * ruptureLength))`
* recent-days: `30`

**Comment by shaefner-usgs** [comment]
[Implemented in PR 23](https://github.com/shaefner-usgs/esc-eq-response/pull/23)
