### ISSUE TITLE
aftershock probabilities 

### ISSUE THREAD

**Issue by paulearle** [shaefner-usgs/esc-eq-response#40]
I have not used this tool in awhile. Very nice improvements! I should have been using it more. 

I'm guessing you are calculating and displaying your own aftershock probabilities?  

Could you put in a link to the aftershock product or display those results so people don't mistakenly report your values instead of the results the public and media are seeing on the webpage?  Great stuff @shaefner-usgs

**Comment by shaefner-usgs** [comment]
App now displays OAF product from feeds so it is consistent with Event Pages.
