### ISSUE TITLE
depth range on search

### ISSUE THREAD

**Issue by paulearle** [shaefner-usgs/esc-eq-response#43]
Hi

Having a depth range on the search criteria in the edit tab would be helpful. This would allow us to pull out a few outliers that mess up the 3D plot.

thanks,
Paul

**Comment by shaefner-usgs** [comment]
This is implemented on master using an interactive range slider below the 3d plots so it doesn't affect the map, summary, and other plots.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/4175182/202057636-2b4722fe-4351-464f-a4de-eb662eead194.png">

Currently, it only filters deep outliers. Is this adequate, or do you anticipate needing to filter shallow outliers as well?

**Comment by PaulStantonEarle** [comment]
This is great! many thanks.
