### ISSUE TITLE
Bug in binning earthquakes by age

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#44]
The binning earthquakes by age has a bug that results in the bins being larger by 1 day. So the events for the past day are actually the past 1.9999 days, past 30 days are actually past 30.9999 days, etc.

Remedy is to change Math.floor to Math.ceil when binning the earthquakes. See PR #42 .

**Comment by shaefner-usgs** [comment]
merged [PR #42](https://github.com/shaefner-usgs/esc-eq-response/pull/42).
