### ISSUE TITLE
Add creation of RTF file to use as an initial file for earthquake summaries

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#48]
Add a button to generate an RTF file for downloading. The RTF file would include information that can be populated directly from the feeds, including images. This would speed up creating the initial earthquake summary documents.

Brad created a template for the RTF file in the ESC Earthquake Response 00_READMEs Google Drive folder.

**Comment by shaefner-usgs** [comment]
Done.
