### ISSUE TITLE
Add more information from feeds to summary page

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#49]
Add more information available in the feeds to the summary page:

## Impact section (before Aftershocks when PAGE product is available)

1. Exposure map from PAGER (map with MMI contours and population density) 
2. Population exposure at MMI levels [`losspager.contents.json/exposures.json`] and list of cities with population and MMI `[losspager.contents.json/cities.json`]

## Location information

1. List of nearby cities (immediately below Time/Location/Depth/Status) [`properties.products.nearby-cities.contents.nearby-cities.json.url`]

**Comment by baagaard-usgs** [comment]
Also include significant events with commentary. There may be multiple sources for this, one from PAGER (losspager) and "Impact Text". I will investigate these sources.

**Comment by baagaard-usgs** [comment]
The historical events from PAGER (losspager) are not quite what we are looking for, especially for CA events.

From Mike Hearne:

> The PAGER team came up with an algorithm about 13 years ago to select up to three events, all within a 400 km radius of the event in question, where the following criteria are met:

> - First event should be the event "most similar" in exposure, and with the fewest fatalities.
> - Second event should also be "similar" in exposure, and with the most fatalities.
> - Third event should be the deadliest and/or highest population exposure event. 

From David Wald:

> As I mentioned, prior: the caveat and known limitation to what goes on PAGER, which is not meant for other general applications, is that we only did exposures back to 1973, the Atlas domain at the time. Population estimates prior are too uncertain. Since we wanted direct comparison of losses and exposures of the current PAGER event and past events in the area with known exposures and losses, that limited the history to a short 50 years.
 
> Those historical exposure and losses are available to the PAGER system separately from Comcat. I think it’s key that you work directly with Comcat rather than the PAGER-CAT flatfile. The new Atlas (V4) will, in fact, have losses back to 1900, and exposures back to 1970. These losses are going to be put into Comcat in the “impact” product, but that product is not yet fully vetted nor populated in Comcat. Your desire to have it would provide one more motivating factor to implement that sooner than later.
 
> Also, the criteria for Atlas V4, which we are writing up, is not CA focused, so some events that you might want to show up with a radius search, but which have low population exposures to strong shaking, may not be in there.

So the path forward seems to be to wait until ComCat has impact information in it. We would then need to use our "historical earthquakes" list to search for impact information (perhaps grab the three with the highest "impact" as sorted by some field within the impact information). 

I don't know if we want to leave the losspager info in there or not. I am tempted to leave it in because in some cases it might be relevant and we can manually remove/ignore it if we find it not useful.

**Comment by PaulStantonEarle** [comment]
There is impact text that is human readable description of damage and deaths etc.
It is called an "impact-text" product. here are some notes from Mike Hearne on how to access these data.

It's a product, but the contents (i.e., the text) you're interested in are not named, so not obtainable through the *published* libcomcat API.  You can still get that text, sample code follows:

#################
from libcomcat.search import get_event_by_id

detail = get_event_by_id('us70008jr5')
itext = detail.getProducts('impact-text')[0]
# the key of the dictionary below is an empty string.
# Weird.
itext_str = itext._product['contents']['']['bytes']
print(itext_str)
#################

should give you  'Some damage to the Custer County courthouse and the Road and Bridge services building at Challis. Avalanches occurred near Stanely and a rockslide occurred near Lowman.\n'

**Comment by PaulStantonEarle** [comment]
sorry for the bold formatting those are supposed to be comments

**Comment by shaefner-usgs** [comment]
These products are all now included under the Summary tab in the latest version.
