### ISSUE TITLE
Add link on summary tab to PDL timeline

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#50]
Add a link from the summary tab to the [PDL timeline](https://jmfee-usgs.github.io/comcat-timeline/timeline.html). Pre-populate page with event id.

**Comment by shaefner-usgs** [comment]
[Added](https://github.com/shaefner-usgs/esc-eq-response/commit/5661e6885ede8e544d189130532a874d5e334665
