### ISSUE TITLE
Error when downloading "Event Summary"

### ISSUE THREAD

**Issue by paulearle** [shaefner-usgs/esc-eq-response#54]
The file I downloaded after hitting the "Event Summary" button contained only this... thanks!

<br />
<b>Warning</b>:  filesize(): stat failed for undefined in <b>/home/www/vhosts/escweb.wr/htdocs/response/php/event-summary/download.php</b> on line <b>18</b><br />
<br />
<b>Warning</b>:  readfile(undefined): failed to open stream: No such file or directory in <b>/home/www/vhosts/escweb.wr/htdocs/response/php/event-summary/download.php</b> on line <b>23</b><br />

**Comment by shaefner-usgs** [comment]
Hi Paul,

This was due to the USGS firewall blocking legit requests @@, but it has been fixed now.
