### ISSUE TITLE
Aftershocks don't load if original parameters exceed limit

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#55]
Aftershocks are not getting loaded even after changing the parameters when the default parameters for the event result in the number of matching events being exceeded.

Test case: Ridgecrest
https://bayquakealliance.org/response/?eqid=ci38457511

I get a 400 error when using the default parameters:
```
GET https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&orderby=time-asc&latitude=35.7695&longitude=-117.5993333&maxradiuskm=150&minmagnitude=-0.05&starttime=2019-07-06T03:19:54 400

Error 400: Bad Request

45047 matching events exceeds search limit of 20000. Modify the search to match fewer events.

Usage details are available from https://earthquake.usgs.gov/fdsnws/event/1

Request:
/fdsnws/event/1/query?format=geojson&orderby=time-asc&latitude=35.7695&longitude=-117.5993333&maxradiuskm=150&minmagnitude=-0.05&starttime=2019-07-06T03:19:54

Request Submitted:
2020-03-07T04:00:30+00:00

Service version:
1.8.1
```

I can adjust the foreshock minimum magnitude to 3.9 and it updates. When I adjust the aftershock minimum magnitude to 3.9, the aftershocks are not reloaded.

Note that if I load the webpage using the URL with the updated parameters, the aftershocks load fine.

**Comment by shaefner-usgs** [comment]
Thanks for letting me know; I fixed it.

https://github.com/shaefner-usgs/esc-eq-response/commit/80661c0c01d66fefdd8f7618b4b1fe426b7d229f
