### ISSUE TITLE
Add magnitude threshold params on edit pane

### ISSUE THREAD

**Issue by shaefner-usgs** [shaefner-usgs/esc-eq-response#7]
Currently all eqs (M 0+) are fetched for both aftershocks and historical seismicity. This might result in poor performance due to plotting too many points on the map. Add a parameter on the edit pane that defaults to a threshold (M 1+ ?), but is configurable by user.

**Comment by baagaard-usgs** [comment]
Implemented in pull request https://github.com/shaefner-usgs/esc-eq-response/pull/15.
