### ISSUE TITLE
Display version number and deployment date on main page

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#79]
I don't see any obvious indication of which version is running on the servers. It would be helpful to display the version number and deployment date on the main page (perhaps in the top right corner). This would make it easy to see if a server is running the latest version and, if something isn't working, what version isn't working.

**Comment by shaefner-usgs** [comment]
[added](https://github.com/shaefner-usgs/esc-eq-response/commit/33ea226a39c03b71643885e8dac69a25be80a04c) to the "info/about" sidebar.
