### ISSUE TITLE
Increase timeout in ComCat queries to increase probability of successful response when traffic is high

### ISSUE THREAD

**Issue by baagaard-usgs** [shaefner-usgs/esc-eq-response#84]

**Comment by shaefner-usgs** [comment]
It's currently set to timeout at 10 secs. I increased the time in development, but it didn't seem to help...the queries still mostly timed out, but just took longer. 

The app includes the functionality to reload any failed fetch (via a reload button in the status bar), so there is a disadvantage to increasing the timeout limit...the user will have to wait longer between failed fetch requests before having the opportunity to attempt a re-fetch.

**Comment by baagaard-usgs** [comment]
We can try 20 secs, but I am not hopeful unless the ComCat performance improves substantially.

**Comment by shaefner-usgs** [comment]
I did more testing, and there are times when feeds fetch successfully after a significant delay, even after 20+ seconds. So I [increased the timeout option to 30s](https://github.com/shaefner-usgs/esc-eq-response/commit/626990283f00c2c423e3f2b9eb91221e81256991).
