### ISSUE TITLE
larger default aftershock radius

### ISSUE THREAD

**Issue by paulearle** [shaefner-usgs/esc-eq-response#9]
This tool is great.
The NZ M7.8 defaults to 30km for aftershock zone.  I suggest at least a fault length or two with a minimum that considers epicentral error.

**Comment by baagaard-usgs** [comment]
Using a rough estimate of rupture length based on magnitude-area relations seems to give a reasonable default across of magnitudes. This change is in pull request https://github.com/shaefner-usgs/esc-eq-response/pull/11.
